services:
  nginx:
    image: ghcr.io/vslvictor7/nginx-geoip-alpine:latest
    container_name: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx/crowdsec
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/include:/etc/nginx/include
      - ./geoip2:/usr/share/GeoIP
    network_mode: host
    restart: unless-stopped
    depends_on:
      - geoip-updater

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      COLLECTIONS: crowdsecurity/nginx
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./crowdsec-config:/etc/crowdsec
      - ./crowdsec-data:/var/lib/crowdsec/data
      - ./crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - ./nginx/logs:/var/log/nginx:ro
    depends_on:
      - nginx

  geoip-updater:
    image: maxmindinc/geoipupdate:latest
    container_name: geoip-updater
    env_file: .env
    volumes:
      - ./geoip2:/usr/share/GeoIP
    environment:
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIP_ACCOUNT_ID}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIP_LICENSE_KEY}
      GEOIPUPDATE_EDITION_IDS: ${GEOIP_EDITION_IDS}
    restart: on-failure