name: Buildar e publicar imagem

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | \
          docker login -u victorvsl7 --password-stdin

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Buildar imagem
        run: |
          docker build . \
            -t victorvsl7/nginx-geoip-alpine:latest \
            -t ghcr.io/victorvsl7/nginx-geoip-alpine:latest

      - name: Publicar imagens no Docker Hub
        run: docker push victorvsl7/nginx-geoip-alpine:latest

      - name: Push GHCR
        run: docker push ghcr.io/victorvsl7/nginx-geoip-alpine:latest